# magicc_shared/llm/client.py

from typing import Optional
from dataclasses import dataclass
from abc import ABC, abstractmethod


@dataclass
class LLMConfig:
    provider: str = "ollama"
    model: str = "qwen-coder:7b"
    api_key: Optional[str] = None
    api_base: Optional[str] = None
    temperature: float = 0.3
    max_tokens: int = 500
    timeout: int = 60


class LLMClient(ABC):
    @abstractmethod
    def generate(self, prompt: str) -> str:
        pass


class OllamaClient(LLMClient):
    def __init__(self, config: LLMConfig):
        self.config = config
        self._api_base = config.api_base or "http://localhost:11434"
        self._requests = None
    
    @property
    def requests(self):
        if self._requests is None:
            try:
                import requests
                self._requests = requests
            except ImportError:
                raise ImportError("requests package required. Run: uv add requests")
        return self._requests
    
    def generate(self, prompt: str) -> str:
        url = f"{self._api_base}/api/generate"
        
        payload = {
            "model": self.config.model,
            "prompt": prompt,
            "stream": False,
            "options": {
                "temperature": self.config.temperature,
                "num_predict": self.config.max_tokens,
            }
        }
        
        try:
            response = self.requests.post(
                url,
                json=payload,
                timeout=self.config.timeout
            )
            response.raise_for_status()
            data = response.json()
            return data.get("response", "").strip()
        except Exception as e:
            return f"[Error: {str(e)}]"


class MockClient(LLMClient):
    def generate(self, prompt: str) -> str:
        return "/**\n * Generated by MagicCoder.\n */"


def create_client(config: LLMConfig) -> LLMClient:
    if config.provider == "ollama":
        return OllamaClient(config)
    elif config.provider == "mock":
        return MockClient(config)
    else:
        raise ValueError(f"Unsupported provider: {config.provider}")